- name: Copy GCS artifact to remote target
  hosts: ui
  become: false

  vars:
    local_artifact_path: "./{{ artifact_name }}"
    remote_artifact_path: "/home/hau/Desktop/HauApp"

  tasks:
    - name: Copy artifact to target
      ansible.posix.synchronize:
        src: "{{ local_artifact_path }}"
        dest: "{{ remote_artifact_path }}"
        mode: push
