- name: Copy GCS artifact to remote target
  hosts: ui
  become: false

  vars:
    local_artifact_path: "./{{ artifact_name }}"
    remote_exe_artifact_path: "/home/hau/HauApp"

  tasks:
    - name: Copy artifact to target
      ansible.posix.synchronize:
        src: "{{ local_artifact_path }}"
        dest: "{{ remote_exe_artifact_path }}"
        mode: push
    - name: Copy the HAU desktop config file
      ansible.posix.synchronize:
        src: "files/Hau.desktop"
        dest: "/home/hau/Desktop"
        mode: push
    
    - name: Mark HAU launcher as trusted by Gnome
      command: gio set /home/hau/Desktop/Hau.desktop "metadata::trusted" true
      become: false
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/hau/.Xauthority"
    
    - name: Copy the BHAU app icon
      ansible.posix.synchronize:
        src: "files/app_icon.jpg"
        dest: "/home/hau/Desktop"
        mode: push
