- name: Install dependency packages for UI
  hosts: ui
  become: true
  become_method: sudo
  become_user: root
  become_flags: '-n'

  vars:
    packages: "{{ lookup('file', './packages.txt').splitlines() }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install packages from list
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    
    - name: Add Kivy PPA
      ansible.builtin.apt_repository:
        repo: ppa:kivy-team/kivy
        state: present
        update_cache: yes  # Automatically runs apt-get update

    - name: Install APT packages
      ansible.builtin.apt:
        name:
          - python3-kivy
          - iperf3
        state: present
        update_cache: yes

    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Upgrade pip packages
      ansible.builtin.pip:
        name:
          - gdown
          - google-cloud-storage
        state: latest
        executable: pip3
    
    - name: Ensure LD_PRELOAD is set in .bashrc
      ansible.builtin.lineinfile:
        path: /home/hau/.bashrc
        line: 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6'
        insertafter: EOF
        create: yes
        owner: hau
        group: hau
        mode: '0644'

